-- List all customers who have made purchases of more than $80.
SELECT * from users;
SELECT * from products;
SELECT * from orders;
SELECT * from orderdetails;

SELECT user_id, total_amount
FROM orders
WHERE total_amount >'80';

-- Retrieve all orders placed in the last 280 days along with the customer name and email.
SELECT user_name, email_id, registered_date
FROM users
WHERE registered_date >'2024-02-01'; 

-- Find the average product price for each category.
SELECT
    category,
    AVG(price) AS average_price
FROM products
GROUP BY category;

-- List all customers who have purchased a product from the category Electronics. 

SELECT DISTINCT u.*
FROM users u
JOIN orders o
    ON u.user_id = o.user_id
JOIN orderdetails od
    ON o.order_id = od.order_id
JOIN products p
    ON od.product_id = p.product_id
WHERE p.category = 'Electronics';

--  Find the total number of products sold and the total revenue generated for each product.

SELECT 
    products.product_id,
    products.product_name,
    SUM(orderdetails.quantity) AS total_products_sold,
    SUM(orderdetails.quantity * products.price) AS total_revenue
    FROM products
    JOIN orderdetails
    ON products.product_id = orderdetails.product_id
GROUP BY 
    products.product_id,
    products.product_name;
    
-- Update the price of all products in the Books category, increasing it by 10%.
SELECT *
FROM products
WHERE category = 'Books';
UPDATE products
SET price = price * 1.10
WHERE category = 'Books'; 

DESCRIBE products; 

-- Remove all orders that were placed before 2020.
SELECT *
FROM orders
WHERE order_date < '2020-01-01'; 

-- write a query to fetch the order details,including customer name,product name,and quantity for orders placed on 2024-05-01 
SELECT 
    u.user_name AS customer_name,
    p.product_name,
    od.quantity
FROM users u
JOIN orders o
    ON u.user_id = o.user_id
JOIN orderdetails od
    ON o.order_id = od.order_id
JOIN products p
    ON od.product_id = p.product_id
WHERE DATE(o.order_date) = '2024-05-01'; 

-- Fetch all customers and the total number of orders they have placed. 
SELECT 
    u.user_id,
    u.user_name AS customer_name,
    COUNT(o.order_id) AS total_orders
FROM users u
LEFT JOIN orders o
    ON u.user_id = o.user_id
GROUP BY 
    u.user_id,
    u.user_name; 
    
-- Retrieve the average rating for all products in the Electronics category.
-- List all customers who purchased more than 1 units of any product, including the product name and total quantity purchased. 
SELECT 
    u.user_name AS customer_name,
    p.product_name,
    SUM(od.quantity) AS total_quantity_purchased
FROM users u
JOIN orders o
    ON u.user_id = o.user_id
JOIN orderdetails od
    ON o.order_id = od.order_id
JOIN products p
    ON od.product_id = p.product_id
GROUP BY 
    u.user_id,
    u.user_name,
    p.product_id,
    p.product_name
HAVING SUM(od.quantity) > 1; 

-- Find the total revenue generated by each category along with the category name.
SELECT 
    p.category,
    SUM(od.quantity * p.price) AS total_revenue
FROM products p
JOIN orderdetails od
    ON p.product_id = od.product_id
GROUP BY p.category;